/**
 * Scoped stylesheet for the two cards, lifted from the Open Design prototype.
 *
 * Generated by `scripts/gen-card-styles.mjs` from
 * `docs/design/dsh-context-snapshot-prototype-v5.html` (sha256 25e24ba4262a…).
 * Edit that prototype and re-run the script — never this file, so the cards
 * cannot drift from the design they must match.
 *
 * @module dsh-context-snapshot-bar/client/styles
 */

/** The plugin's scoped stylesheet. */
export const cardCss = `
.dsh-context-snapshot-bar {
  --bg: oklch(0.982 0.003 250);
      --surface: oklch(1 0 0);
      --surface-soft: oklch(0.973 0.004 250);
      --fg: oklch(0.255 0.012 260);
      --muted: oklch(0.62 0.012 255);
      --faint: oklch(0.76 0.009 255);
      --border: oklch(0.89 0.007 255);
      --accent: oklch(0.61 0.17 256);
      --accent-soft: oklch(0.95 0.035 256);
      --warn: oklch(0.61 0.12 78);
      --danger: oklch(0.59 0.16 28);
      --font-display: "SF Pro Display", "PingFang SC", "Noto Sans CJK SC", sans-serif;
      --font-body: "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", sans-serif;
      --font-mono: "SFMono-Regular", "Cascadia Code", "Noto Sans Mono CJK SC", monospace;
      --shadow: 0 12px 28px oklch(0.3 0.02 255 / 0.06), 0 2px 5px oklch(0.3 0.02 255 / 0.035);
}
.dsh-context-snapshot-bar * {
  box-sizing: border-box;
}
.dsh-context-snapshot-bar html,
.dsh-context-snapshot-bar body {
  min-height: 100%;
}
.dsh-context-snapshot-bar body {
  margin: 0; color: var(--fg); background: var(--bg); font-family: var(--font-body); font-size: 15px; line-height: 1.7;
}
.dsh-context-snapshot-bar button,
.dsh-context-snapshot-bar select,
.dsh-context-snapshot-bar textarea {
  font: inherit;
}
.dsh-context-snapshot-bar button,
.dsh-context-snapshot-bar select {
  color: inherit;
}
.dsh-context-snapshot-bar button {
  cursor: pointer;
}
.dsh-context-snapshot-bar button:focus-visible,
.dsh-context-snapshot-bar select:focus-visible,
.dsh-context-snapshot-bar textarea:focus-visible {
  outline: 3px solid oklch(0.61 0.17 256 / 0.34); outline-offset: 2px;
}
.dsh-context-snapshot-bar .app {
  min-height: 100vh; display: grid; grid-template-columns: 244px minmax(0, 1fr);
}
.dsh-context-snapshot-bar .sidebar {
  border-right: 1px solid var(--border); padding: 24px 14px 18px; display: flex; flex-direction: column; background: var(--surface-soft);
}
.dsh-context-snapshot-bar .brand {
  display: flex; gap: 10px; align-items: center; padding: 4px 7px 25px;
}
.dsh-context-snapshot-bar .brand-mark {
  width: 28px; height: 28px; color: var(--fg);
}
.dsh-context-snapshot-bar .brand-title {
  font: 600 16px/1.2 var(--font-display); letter-spacing: 0;
}
.dsh-context-snapshot-bar .version {
  display: block; margin-top: 3px; color: var(--surface); background: var(--fg); width: max-content; padding: 1px 5px; border-radius: 3px; font: 600 9px/1.2 var(--font-mono); letter-spacing: .04em;
}
.dsh-context-snapshot-bar .new-chat {
  min-height: 46px; width: 100%; border: 1px solid var(--border); border-radius: 12px; background: var(--surface); font-weight: 550; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .new-chat:hover {
  background: var(--surface-soft); border-color: var(--faint);
}
.dsh-context-snapshot-bar .nav-label {
  display: block; color: var(--muted); font-size: 13px; letter-spacing: .02em; margin: 23px 7px 10px;
}
.dsh-context-snapshot-bar .folder {
  display: flex; align-items: center; gap: 8px; min-height: 35px; padding: 0 7px; border-radius: 7px; color: var(--fg);
}
.dsh-context-snapshot-bar .folder.active {
  color: var(--fg); background: oklch(0.93 0.006 255);
}
.dsh-context-snapshot-bar .folder-icon,
.dsh-context-snapshot-bar .line-icon {
  width: 19px; height: 19px; flex: none; stroke: currentColor; fill: none; stroke-width: 1.7; stroke-linecap: round; stroke-linejoin: round;
}
.dsh-context-snapshot-bar .thread {
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; margin: 2px 0; padding: 8px 10px 8px 36px; border-radius: 7px; color: var(--muted); font-size: 14px;
}
.dsh-context-snapshot-bar .thread.current {
  background: oklch(0.93 0.006 255); color: var(--fg); font-weight: 550;
}
.dsh-context-snapshot-bar .settings {
  margin-top: auto; border: 0; background: transparent; padding: 9px 7px; text-align: left; color: var(--muted);
}
.dsh-context-snapshot-bar .settings:hover {
  color: var(--fg);
}
.dsh-context-snapshot-bar .main {
  min-width: 0; display: grid; grid-template-rows: 70px minmax(0, 1fr); background: var(--surface);
}
.dsh-context-snapshot-bar .topbar {
  display: flex; align-items: center; justify-content: space-between; gap: 20px; padding: 0 30px 0 36px; border-bottom: 1px solid var(--border);
}
.dsh-context-snapshot-bar .conversation-title {
  margin: 0; font: 600 18px/1.35 var(--font-display); letter-spacing: 0;
}
.dsh-context-snapshot-bar .top-actions {
  display: flex; align-items: center; gap: 12px; color: var(--muted);
}
.dsh-context-snapshot-bar .mode-label {
  font-size: 13px;
}
.dsh-context-snapshot-bar .quiet-icon {
  height: 36px; width: 36px; display: grid; place-items: center; border: 0; border-radius: 9px; background: transparent; color: var(--muted);
}
.dsh-context-snapshot-bar .quiet-icon:hover {
  background: var(--surface-soft); color: var(--fg);
}
.dsh-context-snapshot-bar .conversation {
  min-height: 0; display: grid; grid-template-columns: minmax(0, 1fr) 270px;
}
.dsh-context-snapshot-bar .chat {
  min-width: 0; display: grid; grid-template-rows: minmax(0, 1fr) auto;
}
.dsh-context-snapshot-bar .messages {
  overflow: auto; padding: 45px clamp(28px, 7vw, 130px) 28px;
}
.dsh-context-snapshot-bar .message {
  max-width: 760px; margin: 0 auto 33px;
}
.dsh-context-snapshot-bar .user-message {
  display: flex; justify-content: flex-end;
}
.dsh-context-snapshot-bar .user-bubble {
  max-width: 500px; padding: 12px 16px; border-radius: 15px 15px 4px 15px; background: var(--surface-soft); border: 1px solid var(--border);
}
.dsh-context-snapshot-bar .assistant-message h2 {
  margin: 0 0 14px; font: 600 26px/1.38 var(--font-display); letter-spacing: 0;
}
.dsh-context-snapshot-bar .assistant-message p {
  max-width: 65ch; margin: 0 0 12px;
}
.dsh-context-snapshot-bar .assistant-message code {
  font-family: var(--font-mono); font-size: .9em; color: oklch(0.42 0.04 256); background: var(--surface-soft); border: 1px solid var(--border); padding: 1px 4px; border-radius: 4px; overflow-wrap: anywhere;
}
.dsh-context-snapshot-bar .message-meta {
  display: flex; gap: 14px; align-items: center; color: var(--muted); margin-top: 18px; font-size: 13px;
}
.dsh-context-snapshot-bar .message-meta button {
  padding: 3px; background: none; border: 0; color: var(--muted);
}
.dsh-context-snapshot-bar .message-meta button:hover {
  color: var(--fg);
}
.dsh-context-snapshot-bar .composer-area {
  padding: 0 clamp(22px, 5vw, 84px) 26px;
}
.dsh-context-snapshot-bar .dock-wrap {
  max-width: 900px; margin: 0 auto;
}
.dsh-context-snapshot-bar .snapshot-card {
  border: 1px solid var(--border); background: var(--surface); border-radius: 12px; overflow: hidden; box-shadow: 0 2px 7px oklch(0.26 0.02 255 / .035);
}
.dsh-context-snapshot-bar .snapshot-toggle {
  width: 100%; min-height: 52px; display: grid; grid-template-columns: auto minmax(0, 1fr) auto auto; align-items: center; gap: 10px; padding: 0 14px; border: 0; background: var(--surface); text-align: left;
}
.dsh-context-snapshot-bar .snapshot-toggle:hover {
  background: var(--surface-soft);
}
.dsh-context-snapshot-bar .snapshot-toggle[aria-expanded="true"] {
  border-bottom: 1px solid var(--border);
}
.dsh-context-snapshot-bar .snapshot-icon {
  display: grid; place-items: center; width: 27px; height: 27px; border-radius: 7px; background: var(--accent-soft); color: var(--accent);
}
.dsh-context-snapshot-bar .snapshot-main {
  display: flex; min-width: 0; gap: 10px; align-items: center; overflow: hidden;
}
.dsh-context-snapshot-bar .snapshot-title {
  white-space: nowrap; font-weight: 550; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .snapshot-summary {
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--muted); font-size: 13px;
}
.dsh-context-snapshot-bar .snapshot-state {
  font-size: 12px; color: var(--muted); white-space: nowrap;
}
.dsh-context-snapshot-bar .snapshot-state.cleared {
  color: var(--danger);
}
.dsh-context-snapshot-bar .snapshot-state.removed {
  color: var(--warn);
}
.dsh-context-snapshot-bar .snapshot-state.disconnected {
  color: var(--warn);
}
.dsh-context-snapshot-bar .chevron {
  width: 17px; height: 17px; transition: transform .18s ease;
}
.dsh-context-snapshot-bar .snapshot-toggle[aria-expanded="true"] .chevron {
  transform: rotate(180deg);
}
.dsh-context-snapshot-bar .snapshot-detail {
  display: none; padding: 15px 16px 16px; max-height: 328px; overflow: auto;
}
.dsh-context-snapshot-bar .snapshot-detail.open {
  display: block;
}
.dsh-context-snapshot-bar .snapshot-note {
  margin: 0 0 13px; color: var(--muted); font-size: 12px; line-height: 1.55;
}
.dsh-context-snapshot-bar .meta-row {
  display: flex; gap: 12px; flex-wrap: wrap; align-items: center; margin: 0 0 13px; font: 12px/1.5 var(--font-mono); color: var(--muted);
}
.dsh-context-snapshot-bar .meta-row span {
  overflow-wrap: anywhere;
}
.dsh-context-snapshot-bar .copy-row {
  display: flex; justify-content: space-between; gap: 12px; align-items: center; padding: 0 0 13px;
}
.dsh-context-snapshot-bar .source {
  min-width: 0; color: var(--muted); font: 12px/1.45 var(--font-mono); overflow-wrap: anywhere;
}
.dsh-context-snapshot-bar .copy-button {
  flex: none; min-height: 32px; padding: 0 10px; border: 1px solid var(--border); border-radius: 7px; color: var(--fg); background: var(--surface); font-size: 12px; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .copy-button:hover {
  background: var(--surface-soft); border-color: var(--faint);
}
.dsh-context-snapshot-bar .section-list {
  display: grid; gap: 10px;
}
.dsh-context-snapshot-bar .section {
  border-top: 1px solid var(--border); padding-top: 10px;
}
.dsh-context-snapshot-bar .section-head {
  display: flex; justify-content: space-between; gap: 12px; align-items: baseline;
}
.dsh-context-snapshot-bar .section-label {
  font-size: 13px; font-weight: 550; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .section-name {
  color: var(--muted); font: 11px/1.5 var(--font-mono); overflow-wrap: anywhere; text-align: right;
}
.dsh-context-snapshot-bar .source-text {
  margin: 7px 0 0; padding: 10px 11px; background: var(--surface-soft); border-radius: 7px; color: oklch(0.37 0.014 255); font: 12px/1.58 var(--font-mono); white-space: pre-wrap; overflow-wrap: anywhere;
}
.dsh-context-snapshot-bar .state-change {
  animation: csb-state-flash 1.1s ease-out;
}
@keyframes csb-state-flash {
from { background: var(--accent-soft); } to { background: transparent; }
}
.dsh-context-snapshot-bar .composer {
  margin-top: 10px; border: 1px solid var(--border); background: var(--surface); border-radius: 18px; box-shadow: var(--shadow); padding: 13px 13px 9px;
}
.dsh-context-snapshot-bar .composer textarea {
  display: block; width: 100%; min-height: 47px; border: 0; resize: none; background: transparent; color: var(--fg); outline: 0; line-height: 1.55;
}
.dsh-context-snapshot-bar .composer textarea::placeholder {
  color: var(--faint);
}
.dsh-context-snapshot-bar .composer-bottom {
  display: flex; align-items: center; justify-content: space-between; gap: 10px;
}
.dsh-context-snapshot-bar .scope {
  display: flex; align-items: center; gap: 7px; min-width: 0; font-size: 13px; color: var(--muted);
}
.dsh-context-snapshot-bar .scope span {
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}
.dsh-context-snapshot-bar .send {
  width: 37px; height: 37px; border: 0; border-radius: 50%; display: grid; place-items: center; color: var(--surface); background: var(--accent);
}
.dsh-context-snapshot-bar .send:hover {
  background: oklch(0.53 0.17 256); transform: translateY(-1px);
}
.dsh-context-snapshot-bar .send:active {
  transform: translateY(1px);
}
.dsh-context-snapshot-bar .demo-panel {
  border-left: 1px solid var(--border); background: var(--surface-soft); padding: 28px 20px;
}
.dsh-context-snapshot-bar .demo-eyebrow {
  margin: 0 0 9px; font-size: 11px; color: var(--muted); font-weight: 600; letter-spacing: .08em; text-transform: uppercase;
}
.dsh-context-snapshot-bar .demo-panel h3 {
  margin: 0; font: 600 17px/1.4 var(--font-display); letter-spacing: 0;
}
.dsh-context-snapshot-bar .demo-panel p {
  margin: 7px 0 18px; color: var(--muted); font-size: 13px; line-height: 1.6;
}
.dsh-context-snapshot-bar .demo-control {
  display: grid; gap: 7px;
}
.dsh-context-snapshot-bar .demo-control label {
  color: var(--fg); font-size: 13px; font-weight: 550; letter-spacing: .02em;
}
.dsh-context-snapshot-bar select {
  min-height: 39px; border: 1px solid var(--border); border-radius: 8px; background: var(--surface); padding: 0 8px; font-size: 13px;
}
.dsh-context-snapshot-bar select:hover {
  border-color: var(--faint);
}
.dsh-context-snapshot-bar .demo-divider {
  height: 1px; background: var(--border); margin: 25px 0 17px;
}
.dsh-context-snapshot-bar .demo-list {
  margin: 0; padding: 0; list-style: none; color: var(--muted); font-size: 12px; line-height: 1.65;
}
.dsh-context-snapshot-bar .demo-list li {
  position: relative; padding-left: 12px; margin-bottom: 8px;
}
.dsh-context-snapshot-bar .demo-list li::before {
  content: ""; position: absolute; top: .66em; left: 0; width: 4px; height: 4px; border-radius: 50%; background: var(--faint);
}
.dsh-context-snapshot-bar .mobile-demo {
  display: none;
}
@media (max-width: 1180px) {
  .dsh-context-snapshot-bar .conversation {
    grid-template-columns: minmax(0, 1fr) 230px;
  }
  .dsh-context-snapshot-bar .demo-panel {
    padding: 25px 16px;
  }
  .dsh-context-snapshot-bar .messages {
    padding-left: 48px; padding-right: 48px;
  }
}
@media (max-width: 1024px) {
  .dsh-context-snapshot-bar .app {
    grid-template-columns: 206px minmax(0, 1fr);
  }
  .dsh-context-snapshot-bar .conversation {
    display: block;
  }
  .dsh-context-snapshot-bar .demo-panel {
    display: none;
  }
  .dsh-context-snapshot-bar .mobile-demo {
    display: block; padding: 12px clamp(22px, 5vw, 84px) 0; border-bottom: 1px solid var(--border);
  }
  .dsh-context-snapshot-bar .mobile-demo-inner {
    max-width: 900px; margin: 0 auto; display: flex; align-items: center; justify-content: space-between; gap: 12px; color: var(--muted); font-size: 12px;
  }
  .dsh-context-snapshot-bar .mobile-demo select {
    min-height: 34px; max-width: 210px;
  }
}
@media (max-width: 720px) {
  .dsh-context-snapshot-bar .app {
    display: block;
  }
  .dsh-context-snapshot-bar .sidebar {
    display: none;
  }
  .dsh-context-snapshot-bar .main {
    min-height: 100vh; grid-template-rows: 58px minmax(0, 1fr);
  }
  .dsh-context-snapshot-bar .topbar {
    padding: 0 15px;
  }
  .dsh-context-snapshot-bar .conversation-title {
    font-size: 16px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  }
  .dsh-context-snapshot-bar .mode-label {
    display: none;
  }
  .dsh-context-snapshot-bar .top-actions {
    gap: 2px;
  }
  .dsh-context-snapshot-bar .messages {
    padding: 28px 18px 18px;
  }
  .dsh-context-snapshot-bar .assistant-message h2 {
    font-size: 22px;
  }
  .dsh-context-snapshot-bar .message {
    margin-bottom: 26px;
  }
  .dsh-context-snapshot-bar .composer-area {
    padding: 0 12px 16px;
  }
  .dsh-context-snapshot-bar .mobile-demo {
    padding: 9px 12px 0;
  }
  .dsh-context-snapshot-bar .mobile-demo-inner {
    align-items: flex-start;
  }
  .dsh-context-snapshot-bar .mobile-demo .demo-label {
    padding-top: 7px;
  }
  .dsh-context-snapshot-bar .mobile-demo select {
    max-width: 185px;
  }
  .dsh-context-snapshot-bar .snapshot-main {
    gap: 7px;
  }
  .dsh-context-snapshot-bar .snapshot-summary {
    display: none;
  }
  .dsh-context-snapshot-bar .snapshot-detail {
    max-height: 295px;
  }
  .dsh-context-snapshot-bar .section-head {
    align-items: flex-start; flex-direction: column; gap: 1px;
  }
  .dsh-context-snapshot-bar .section-name {
    text-align: left;
  }
  .dsh-context-snapshot-bar .copy-row {
    align-items: flex-start; flex-direction: column; gap: 7px;
  }
}
@media (prefers-color-scheme: dark) {
  .dsh-context-snapshot-bar {
    --bg: oklch(0.16 0.012 255); --surface: oklch(0.19 0.012 255); --surface-soft: oklch(0.22 0.012 255); --fg: oklch(0.92 0.008 255); --muted: oklch(0.7 0.012 255); --faint: oklch(0.52 0.012 255); --border: oklch(0.31 0.012 255); --accent-soft: oklch(0.26 0.055 256); --shadow: 0 12px 28px oklch(0.06 0.012 255 / .34);
  }
  .dsh-context-snapshot-bar .folder.active,
.dsh-context-snapshot-bar .thread.current {
    background: oklch(0.27 0.012 255);
  }
  .dsh-context-snapshot-bar .source-text {
    color: oklch(0.82 0.012 255);
  }
  .dsh-context-snapshot-bar .assistant-message code {
    color: oklch(0.76 0.1 256);
  }
}
.dsh-context-snapshot-bar html,
.dsh-context-snapshot-bar body {
  height: 100%; overflow: hidden;
}
.dsh-context-snapshot-bar .app {
  height: 100dvh; min-height: 0; overflow: hidden;
}
.dsh-context-snapshot-bar .main,
.dsh-context-snapshot-bar .chat,
.dsh-context-snapshot-bar .messages {
  min-height: 0;
}
.dsh-context-snapshot-bar .main,
.dsh-context-snapshot-bar .chat {
  height: 100%;
}
.dsh-context-snapshot-bar .snapshot-detail {
  max-height: min(328px, 40dvh);
}
.dsh-context-snapshot-bar .demo-panel {
  min-height: 0; overflow: auto;
}
.dsh-context-snapshot-bar .snapshot-main,
.dsh-context-snapshot-bar .snapshot-state {
  min-width: 0;
}
.dsh-context-snapshot-bar .snapshot-state {
  max-width: 160px; overflow: hidden; text-overflow: ellipsis;
}
@media (max-width: 1024px) {
  .dsh-context-snapshot-bar .conversation {
    display: grid; grid-template-columns: minmax(0, 1fr);
  }
  .dsh-context-snapshot-bar .chat {
    grid-template-rows: auto minmax(0, 1fr) auto;
  }
  .dsh-context-snapshot-bar .mobile-demo {
    padding-bottom: 10px;
  }
}
@media (max-width: 720px) {
  .dsh-context-snapshot-bar .main {
    min-height: 0;
  }
  .dsh-context-snapshot-bar .snapshot-toggle {
    gap: 7px; padding: 0 10px;
  }
  .dsh-context-snapshot-bar .snapshot-title {
    font-size: 13px; letter-spacing: 0;
  }
  .dsh-context-snapshot-bar .snapshot-main {
    flex-direction: column; align-items: flex-start; gap: 0;
  }
  .dsh-context-snapshot-bar .snapshot-summary {
    display: block; max-width: 100%; font-size: 11px;
  }
  .dsh-context-snapshot-bar .snapshot-state {
    max-width: 112px; font-size: 11px;
  }
  .dsh-context-snapshot-bar .snapshot-detail {
    max-height: min(295px, 34dvh);
  }
}
@media (prefers-reduced-motion: reduce) {
  .dsh-context-snapshot-bar .state-change {
    animation: none;
  }
  .dsh-context-snapshot-bar .chevron {
    transition: none;
  }
}
.dsh-context-snapshot-bar .dock-wrap {
  max-height: min(556px, 68dvh); display: flex; flex-direction: column; min-height: 0; padding: 1px 1px 0;
}
.dsh-context-snapshot-bar .trajectory-card,
.dsh-context-snapshot-bar .snapshot-card {
  display: flex; flex-direction: column; min-height: 54px; flex: 0 1 auto;
}
.dsh-context-snapshot-bar .trajectory-toggle,
.dsh-context-snapshot-bar .snapshot-toggle {
  flex: none;
}
.dsh-context-snapshot-bar .trajectory-detail,
.dsh-context-snapshot-bar .snapshot-detail {
  min-height: 0; flex: 0 1 auto;
}
.dsh-context-snapshot-bar .composer {
  position: relative; flex: none;
}
.dsh-context-snapshot-bar .trajectory-card {
  margin-bottom: 9px; border: 1px solid var(--border); border-radius: 12px; overflow: hidden; background: var(--surface); box-shadow: 0 2px 7px oklch(0.26 0.02 255 / .035);
}
.dsh-context-snapshot-bar .trajectory-toggle {
  width: 100%; min-height: 54px; display: grid; grid-template-columns: 28px minmax(0, 1fr) auto 17px; align-items: center; gap: 10px; padding: 0 14px; border: 0; background: var(--surface); color: var(--fg); text-align: left;
}
.dsh-context-snapshot-bar .trajectory-toggle:hover {
  background: var(--surface-soft);
}
.dsh-context-snapshot-bar .trajectory-toggle[aria-expanded="true"] {
  border-bottom: 1px solid var(--border);
}
.dsh-context-snapshot-bar .trajectory-glyph {
  display: grid; place-items: center; width: 27px; height: 27px; border-radius: 7px; color: var(--fg); background: var(--surface-soft); font: 600 16px/1 var(--font-mono);
}
.dsh-context-snapshot-bar .trajectory-label {
  display: flex; gap: 9px; align-items: center; min-width: 0;
}
.dsh-context-snapshot-bar .trajectory-title {
  white-space: nowrap; font-weight: 550; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .trajectory-strip {
  display: flex; gap: 4px; min-width: 0; overflow: hidden;
}
.dsh-context-snapshot-bar .strip-token {
  flex: none; border: 1px solid var(--border); border-radius: 999px; padding: 1px 6px; color: var(--muted); background: var(--surface); font-size: 10px; line-height: 1.5; letter-spacing: .01em;
}
.dsh-context-snapshot-bar .trajectory-state {
  color: var(--muted); white-space: nowrap; font-size: 12px;
}
.dsh-context-snapshot-bar .trajectory-toggle .chevron {
  transition: transform .18s cubic-bezier(.2,0,0,1);
}
.dsh-context-snapshot-bar .trajectory-toggle[aria-expanded="true"] .chevron {
  transform: rotate(180deg);
}
.dsh-context-snapshot-bar .trajectory-detail {
  display: none; padding: 13px 14px 14px; max-height: min(342px, 39dvh); overflow: auto;
}
.dsh-context-snapshot-bar .trajectory-detail.open {
  display: block;
}
.dsh-context-snapshot-bar .trajectory-intro {
  display: flex; flex-direction: column; justify-content: space-between; gap: 5px; align-items: flex-start; margin: 0 0 11px;
}
.dsh-context-snapshot-bar .trajectory-intro p {
  max-width: 64ch; margin: 0; color: var(--muted); font-size: 12px; line-height: 1.55;
}
.dsh-context-snapshot-bar .context-status {
  flex: none; max-width: 100%; white-space: normal; border-radius: 999px; padding: 2px 7px; color: var(--muted); background: var(--surface-soft); font: 11px/1.55 var(--font-mono); white-space: normal;
}
.dsh-context-snapshot-bar .context-status.committing {
  color: var(--fg); background: var(--accent-soft);
}
.dsh-context-snapshot-bar .context-status.error {
  color: var(--danger); background: oklch(0.96 0.025 28);
}
.dsh-context-snapshot-bar .context-track {
  display: grid; gap: 9px; min-width: 0;
}
.dsh-context-snapshot-bar .track-caption {
  display: flex; justify-content: space-between; gap: 12px; color: var(--muted); font-size: 11px; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .turn-segment {
  display: grid; gap: 7px; min-width: 0;
}
.dsh-context-snapshot-bar .turn-label {
  display: flex; align-items: center; gap: 7px; color: var(--muted); font: 11px/1.4 var(--font-mono);
}
.dsh-context-snapshot-bar .turn-label::after {
  content: ""; height: 1px; min-width: 12px; flex: 1; background: var(--border);
}
.dsh-context-snapshot-bar .context-node {
  position: relative; width: 100%; display: grid; grid-template-columns: 58px minmax(0, 1fr) auto; align-items: start; gap: 9px; border: 1px solid var(--border); border-radius: 9px; padding: 9px 10px; background: var(--surface); color: var(--fg); text-align: left; transition: background .18s cubic-bezier(.2,0,0,1), border-color .18s cubic-bezier(.2,0,0,1), transform .42s cubic-bezier(.2,0,0,1), opacity .42s cubic-bezier(.2,0,0,1);
}
.dsh-context-snapshot-bar .context-node:hover {
  background: var(--surface-soft); border-color: var(--faint);
}
.dsh-context-snapshot-bar .context-node.selected {
  border-color: var(--accent); box-shadow: 0 0 0 2px oklch(0.61 0.17 256 / .13);
}
.dsh-context-snapshot-bar .context-node.system {
  color: var(--muted); background: var(--surface-soft); border-style: dashed;
}
.dsh-context-snapshot-bar .context-node.injected {
  background: oklch(0.975 0.009 256);
}
.dsh-context-snapshot-bar .context-node.human {
  background: oklch(0.985 0.004 70);
}
.dsh-context-snapshot-bar .context-node.summary {
  border-color: oklch(0.67 0.08 152); background: oklch(0.97 0.018 152);
}
.dsh-context-snapshot-bar .context-node.checkpoint {
  background: oklch(0.97 0.018 152);
}
.dsh-context-snapshot-bar .tool-result.pruned {
  background: oklch(0.976 0.022 78);
}
.dsh-context-snapshot-bar .context-node.entering {
  animation: csb-node-enter .42s cubic-bezier(.2,0,0,1) both;
}
.dsh-context-snapshot-bar .context-node.contracting {
  opacity: 0; transform: scale(.975); pointer-events: none;
}
.dsh-context-snapshot-bar .node-kind {
  color: var(--muted); font: 11px/1.42 var(--font-mono);
}
.dsh-context-snapshot-bar .node-body {
  min-width: 0;
}
.dsh-context-snapshot-bar .node-title {
  display: block; font-size: 12px; font-weight: 550; letter-spacing: .01em;
}
.dsh-context-snapshot-bar .node-excerpt {
  display: block; margin-top: 2px; color: var(--muted); font-size: 12px; line-height: 1.45; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}
.dsh-context-snapshot-bar .node-meta {
  color: var(--muted); font: 10px/1.5 var(--font-mono); white-space: nowrap;
}
.dsh-context-snapshot-bar .tool-pairs {
  grid-column: 2 / -1; display: grid; gap: 5px; margin-top: 1px;
}
.dsh-context-snapshot-bar .tool-pair {
  display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 5px;
}
.dsh-context-snapshot-bar .tool-call,
.dsh-context-snapshot-bar .tool-result {
  min-width: 0; border-radius: 6px; padding: 5px 7px; font: 10px/1.45 var(--font-mono); overflow-wrap: anywhere;
}
.dsh-context-snapshot-bar .tool-call {
  border: 1px solid var(--border); color: var(--fg); background: var(--surface-soft);
}
.dsh-context-snapshot-bar .tool-result {
  position: relative; border: 1px solid var(--border); color: var(--muted); background: var(--surface);
}
.dsh-context-snapshot-bar .tool-result::before {
  content: "↳"; margin-right: 4px; color: var(--muted);
}
.dsh-context-snapshot-bar .tool-chip-label {
  display: block; color: var(--muted); font-family: var(--font-body); font-size: 10px; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .inspect-panel {
  margin-top: 10px; border-top: 1px solid var(--border); padding-top: 10px;
}
.dsh-context-snapshot-bar .inspect-head {
  display: flex; justify-content: space-between; gap: 12px; align-items: baseline;
}
.dsh-context-snapshot-bar .inspect-title {
  font-size: 12px; font-weight: 550; letter-spacing: .02em;
}
.dsh-context-snapshot-bar .inspect-meta {
  color: var(--muted); font: 10px/1.5 var(--font-mono); text-align: right;
}
.dsh-context-snapshot-bar .inspect-copy {
  margin: 5px 0 0; color: var(--muted); font-size: 12px; line-height: 1.55;
}
.dsh-context-snapshot-bar .summary-points {
  margin: 6px 0 0; padding: 0 0 0 17px; color: var(--muted); font-size: 12px; line-height: 1.55;
}
.dsh-context-snapshot-bar .summary-points li {
  margin: 2px 0;
}
.dsh-context-snapshot-bar .archive-panel {
  margin-top: 10px; border-top: 1px solid var(--border); padding-top: 9px; color: var(--muted); font-size: 11px; line-height: 1.52;
}
.dsh-context-snapshot-bar .archive-panel summary {
  cursor: pointer; color: var(--muted); letter-spacing: .01em;
}
.dsh-context-snapshot-bar .archive-panel summary:hover {
  color: var(--fg);
}
.dsh-context-snapshot-bar .archive-panel p {
  margin: 8px 0 0;
}
.dsh-context-snapshot-bar .archive-nodes {
  display: flex; align-items: center; flex-wrap: wrap; gap: 5px; margin-top: 8px;
}
.dsh-context-snapshot-bar .archive-nodes span {
  border: 1px dashed var(--border); border-radius: 5px; padding: 2px 5px; opacity: .66;
}
.dsh-context-snapshot-bar .archive-nodes .archive-arrow {
  border: 0; padding: 0; opacity: 1;
}
.dsh-context-snapshot-bar .archive-nodes .archive-summary {
  border-style: solid; color: var(--fg); opacity: 1; background: oklch(0.97 0.018 152);
}
.dsh-context-snapshot-bar .replay-note {
  margin: 10px 0 0; color: var(--muted); font-size: 11px; line-height: 1.52;
}
.dsh-context-snapshot-bar .demo-motion {
  display: grid; gap: 8px; margin-top: 18px;
}
.dsh-context-snapshot-bar .demo-button-row {
  display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px;
}
.dsh-context-snapshot-bar .demo-button {
  min-height: 34px; border: 1px solid var(--border); border-radius: 7px; background: var(--surface); color: var(--fg); font-size: 12px; letter-spacing: .01em;
}
.dsh-context-snapshot-bar .demo-button:hover {
  background: var(--surface-soft); border-color: var(--faint);
}
.dsh-context-snapshot-bar .demo-button.primary {
  border-color: var(--accent); background: var(--accent); color: var(--surface);
}
.dsh-context-snapshot-bar .demo-button.primary:hover {
  background: oklch(0.53 0.17 256);
}
.dsh-context-snapshot-bar .demo-playback {
  color: var(--muted); font-size: 11px;
}
@keyframes csb-node-enter {
from { opacity: 0; transform: translateY(9px); } to { opacity: 1; transform: translateY(0); }
}
@media (max-width: 720px) {
  .dsh-context-snapshot-bar .dock-wrap {
    max-height: min(596px, 66dvh);
  }
  .dsh-context-snapshot-bar .trajectory-toggle {
    grid-template-columns: 25px minmax(0, 1fr) auto 15px; gap: 7px; padding: 0 10px;
  }
  .dsh-context-snapshot-bar .trajectory-label {
    display: grid; gap: 1px;
  }
  .dsh-context-snapshot-bar .trajectory-title {
    font-size: 13px;
  }
  .dsh-context-snapshot-bar .trajectory-strip {
    max-width: 188px;
  }
  .dsh-context-snapshot-bar .strip-token {
    padding: 0 5px; font-size: 9px;
  }
  .dsh-context-snapshot-bar .trajectory-state {
    max-width: 66px; overflow: hidden; text-overflow: ellipsis; font-size: 11px;
  }
  .dsh-context-snapshot-bar .trajectory-detail {
    max-height: min(320px, 37dvh); padding: 11px 10px 12px;
  }
  .dsh-context-snapshot-bar .trajectory-intro {
    display: block;
  }
  .dsh-context-snapshot-bar .context-status {
    display: inline-block; margin-top: 5px;
  }
  .dsh-context-snapshot-bar .context-node {
    grid-template-columns: 51px minmax(0, 1fr); gap: 7px; padding: 8px;
  }
  .dsh-context-snapshot-bar .node-meta {
    display: none;
  }
  .dsh-context-snapshot-bar .tool-pairs {
    grid-column: 2;
  }
  .dsh-context-snapshot-bar .tool-pair {
    grid-template-columns: 1fr;
  }
  .dsh-context-snapshot-bar .inspect-meta {
    max-width: 46%;
  }
}
.dsh-context-snapshot-bar .mobile-demo-controls {
  display: flex; align-items: center; gap: 6px; min-width: 0;
}
.dsh-context-snapshot-bar .mobile-demo-controls select {
  min-width: 0; max-width: 156px;
}
.dsh-context-snapshot-bar .mobile-demo-controls .demo-button {
  min-width: 54px;
}
@media (max-width: 720px) {
  .dsh-context-snapshot-bar .mobile-demo-inner {
    flex-wrap: wrap;
  }
  .dsh-context-snapshot-bar .mobile-demo-controls {
    width: 100%;
  }
  .dsh-context-snapshot-bar .mobile-demo-controls select {
    flex: 1 1 0; max-width: none;
  }
}
@media (prefers-reduced-motion: reduce) {
  .dsh-context-snapshot-bar .context-node,
.dsh-context-snapshot-bar .trajectory-toggle .chevron {
    transition: none;
  }
  .dsh-context-snapshot-bar .context-node.entering {
    animation: none;
  }
}
@media (prefers-color-scheme: dark) {
  .dsh-context-snapshot-bar .context-node.injected {
    background: oklch(0.23 0.027 256);
  }
  .dsh-context-snapshot-bar .context-node.human {
    background: oklch(0.24 0.012 75);
  }
  .dsh-context-snapshot-bar .context-node.summary,
.dsh-context-snapshot-bar .context-node.checkpoint,
.dsh-context-snapshot-bar .archive-nodes .archive-summary {
    background: oklch(0.25 0.033 152);
  }
  .dsh-context-snapshot-bar .tool-result.pruned {
    background: oklch(0.27 0.03 78);
  }
  .dsh-context-snapshot-bar .context-status.error {
    background: oklch(0.25 0.034 28);
  }
}
.dsh-context-snapshot-bar .overview-wrap {
  position: sticky; top: -13px; z-index: 2; padding: 8px 0 10px; background: var(--surface); border-bottom: 1px solid var(--border); margin-bottom: 10px;
}
.dsh-context-snapshot-bar .overview-caption {
  display: flex; justify-content: space-between; color: var(--muted); font-size: 11px; margin-bottom: 7px;
}
.dsh-context-snapshot-bar .overview-flow {
  display: flex; align-items: center; gap: 4px; flex-wrap: wrap;
}
.dsh-context-snapshot-bar .overview-chip {
  display: flex; flex-direction: column; align-items: center; justify-content: center; min-width: 34px; min-height: 36px; padding: 3px 5px; border: 1px solid var(--border); border-radius: 6px; font-size: 10px; background: var(--surface-soft); color: var(--muted);
}
.dsh-context-snapshot-bar .overview-chip.human {
  background: oklch(0.96 0.025 78); color: oklch(0.42 0.055 78);
}
.dsh-context-snapshot-bar .overview-chip.injected {
  background: var(--accent-soft); color: var(--accent);
}
.dsh-context-snapshot-bar .overview-chip.summary {
  background: oklch(0.95 0.035 152); color: oklch(0.42 0.09 152); border-color: oklch(0.72 0.08 152); min-width: 68px;
}
.dsh-context-snapshot-bar .overview-chip small {
  font-size: 8px;
}
.dsh-context-snapshot-bar .overview-group {
  display: flex; align-items: center; gap: 3px; padding: 3px; border: 1px dashed var(--border); border-radius: 8px;
}
.dsh-context-snapshot-bar .overview-group.contracting {
  animation: csb-group-contract .48s ease-in both;
}
.dsh-context-snapshot-bar .overview-chip.entering {
  animation: csb-node-enter .42s ease-out both;
}
.dsh-context-snapshot-bar .overview-chip.pruned {
  animation: csb-result-prune .5s ease-out both; background: oklch(0.96 0.04 78);
}
.dsh-context-snapshot-bar .assistant-cluster.contracting {
  animation: csb-group-contract .48s ease-in both;
}
.dsh-context-snapshot-bar .context-node.contracting {
  animation: csb-group-contract .48s ease-in both;
}
@keyframes csb-group-contract {
from { opacity: 1; transform: scale(1); } to { opacity: 0; transform: scale(.65); }
}
@keyframes csb-result-prune {
0% { transform: scale(1); } 45% { transform: scale(.8); } 100% { transform: scale(1); }
}
@media (max-width: 720px) {
  .dsh-context-snapshot-bar .overview-wrap {
    top: -11px;
  }
  .dsh-context-snapshot-bar .overview-chip {
    min-width: 26px; padding: 2px 3px; font-size: 9px;
  }
  .dsh-context-snapshot-bar .overview-flow,
.dsh-context-snapshot-bar .overview-group {
    gap: 2px;
  }
  .dsh-context-snapshot-bar .overview-group {
    padding: 2px;
  }
}
@media (prefers-reduced-motion: reduce) {
  .dsh-context-snapshot-bar .overview-chip,
.dsh-context-snapshot-bar .overview-group,
.dsh-context-snapshot-bar .assistant-cluster,
.dsh-context-snapshot-bar .context-node {
    animation: none !important; transition: none !important;
  }
}
.dsh-context-snapshot-bar .app {
  grid-template-columns: 210px minmax(0,1fr);
}
.dsh-context-snapshot-bar .conversation {
  display:grid; grid-template-columns:minmax(0,1fr) 360px; overflow:hidden;
}
.dsh-context-snapshot-bar .conversation.panel-closed {
  grid-template-columns:minmax(0,1fr);
}
.dsh-context-snapshot-bar .conversation.panel-closed .context-sidebar {
  display:none;
}
.dsh-context-snapshot-bar .chat {
  grid-template-rows:minmax(0,1fr) auto;
}
.dsh-context-snapshot-bar .mobile-demo {
  display:none;
}
.dsh-context-snapshot-bar .messages {
  padding:36px clamp(20px,3vw,56px);
}
.dsh-context-snapshot-bar .composer-area {
  padding:0 24px 12px;
}
.dsh-context-snapshot-bar .dock-wrap {
  max-height:none; padding:0;
}
.dsh-context-snapshot-bar .composer {
  margin-top:0; flex:none;
}
.dsh-context-snapshot-bar .snapshot-card {
  margin-top:8px; min-height:44px; border-radius:8px; box-shadow:none; flex:none;
}
.dsh-context-snapshot-bar .snapshot-toggle {
  min-height:44px; padding:0 10px; gap:7px;
}
.dsh-context-snapshot-bar .snapshot-icon {
  width:20px; height:20px; background:transparent; color:var(--muted);
}
.dsh-context-snapshot-bar .snapshot-title {
  font-size:12px;
}
.dsh-context-snapshot-bar .snapshot-main {
  flex-direction:column; align-items:flex-start; gap:0;
}
.dsh-context-snapshot-bar .snapshot-summary {
  display:block; font-size:11px;
}
.dsh-context-snapshot-bar .snapshot-state {
  font-size:11px; max-width:130px;
}
.dsh-context-snapshot-bar .snapshot-toggle[aria-expanded="true"] {
  border-bottom:0; background:var(--surface-soft);
}
.dsh-context-snapshot-bar .context-sidebar {
  display:flex; flex-direction:column; min-width:0; min-height:0; border-left:1px solid var(--border); background:var(--bg);
}
.dsh-context-snapshot-bar .context-sidebar-header {
  display:flex; align-items:center; justify-content:space-between; padding:6px 16px; font-size:13px; font-weight:550;
}
.dsh-context-snapshot-bar .context-sidebar-header button {
  width:44px; height:44px; border:0; background:transparent; color:var(--fg); font-size:22px; border-radius:7px;
}
.dsh-context-snapshot-bar .context-sidebar-header button:hover {
  background:var(--surface-soft);
}
.dsh-context-snapshot-bar .context-tabs {
  display:flex; border-bottom:1px solid var(--border); padding:0 12px; gap:16px;
}
.dsh-context-snapshot-bar .context-tabs button {
  min-height:44px; padding:0 4px; border:0; border-bottom:2px solid transparent; background:transparent; color:var(--fg); font-size:12px;
}
.dsh-context-snapshot-bar .context-tabs button[aria-pressed="true"] {
  border-bottom-color:var(--accent); font-weight:600;
}
.dsh-context-snapshot-bar .context-tabs button:hover {
  background:var(--surface-soft);
}
.dsh-context-snapshot-bar .context-sidebar-body {
  flex:1; min-height:0; display:flex; flex-direction:column; padding:12px; overflow:auto;
}
.dsh-context-snapshot-bar .trajectory-card {
  margin:0; flex:1; min-height:0; box-shadow:none; border-radius:9px;
}
.dsh-context-snapshot-bar .trajectory-toggle {
  grid-template-columns:minmax(0,1fr) auto 15px; padding:0 12px; gap:6px; min-height:48px;
}
.dsh-context-snapshot-bar .trajectory-glyph,
.dsh-context-snapshot-bar .trajectory-strip {
  display:none;
}
.dsh-context-snapshot-bar .trajectory-card:has(.trajectory-toggle[aria-expanded="false"]) {
  flex:none;
}
.dsh-context-snapshot-bar .trajectory-title {
  font-size:13px;
}
.dsh-context-snapshot-bar .trajectory-label {
  display:block;
}
.dsh-context-snapshot-bar .trajectory-state {
  font-size:10px; max-width:none;
}
.dsh-context-snapshot-bar .trajectory-detail {
  flex:1; max-height:none; padding:12px;
}
.dsh-context-snapshot-bar .trajectory-intro {
  margin-bottom:15px;
}
.dsh-context-snapshot-bar .track-caption {
  display:none;
}
.dsh-context-snapshot-bar .context-track {
  position:relative; gap:18px; padding-left:13px; border-left:1px solid var(--border); margin-left:4px;
}
.dsh-context-snapshot-bar .turn-segment {
  gap:3px;
}
.dsh-context-snapshot-bar .turn-label {
  margin-bottom:7px; font-family:var(--font-body); line-height:1.6;
}
.dsh-context-snapshot-bar .turn-label::after {
  display:none;
}
.dsh-context-snapshot-bar .context-node {
  display:grid; grid-template-columns:minmax(0,1fr); gap:2px; border:0; border-radius:6px; padding:8px; min-height:44px; box-shadow:none;
}
.dsh-context-snapshot-bar .context-node::before {
  content:""; position:absolute; left:-18px; top:16px; width:7px; height:7px; border:1px solid var(--border); border-radius:50%; background:var(--surface);
}
.dsh-context-snapshot-bar .context-node.human::before {
  background:var(--fg); border-color:var(--fg);
}
.dsh-context-snapshot-bar .context-node.system,
.dsh-context-snapshot-bar .context-node.injected,
.dsh-context-snapshot-bar .context-node.human {
  background:transparent;
}
.dsh-context-snapshot-bar .context-node.selected {
  background:var(--surface-soft); box-shadow:none; border:0;
}
.dsh-context-snapshot-bar .context-node:hover {
  background:var(--surface-soft);
}
.dsh-context-snapshot-bar .node-kind {
  font:11px/1.5 var(--font-body);
}
.dsh-context-snapshot-bar .node-meta {
  display:none;
}
.dsh-context-snapshot-bar .node-title {
  font-size:12px; font-weight:550;
}
.dsh-context-snapshot-bar .node-excerpt {
  display:none;
}
.dsh-context-snapshot-bar .tool-pairs {
  margin:0 0 5px 8px; padding-left:9px; border-left:1px solid var(--border);
}
.dsh-context-snapshot-bar .tool-pair {
  grid-template-columns:minmax(0,1fr); gap:3px;
}
.dsh-context-snapshot-bar .tool-call,
.dsh-context-snapshot-bar .tool-result {
  min-height:44px; border:0; font-size:11px; padding:7px; text-align:left;
}
.dsh-context-snapshot-bar .tool-result {
  background:transparent;
}
.dsh-context-snapshot-bar .tool-call:hover,
.dsh-context-snapshot-bar .tool-result:hover {
  background:var(--surface-soft); color:var(--fg);
}
.dsh-context-snapshot-bar .inspect-panel {
  margin:0 0 8px 8px; padding:8px; border:1px solid var(--border); border-radius:6px; background:var(--surface); overflow-wrap:anywhere;
}
.dsh-context-snapshot-bar .inspect-head {
  display:block;
}
.dsh-context-snapshot-bar .inspect-meta {
  display:block; text-align:left; margin-top:3px;
}
.dsh-context-snapshot-bar .inspect-copy {
  color:var(--fg);
}
.dsh-context-snapshot-bar .snapshot-pane {
  border:1px solid var(--border); border-radius:9px; background:var(--surface); padding:12px;
}
.dsh-context-snapshot-bar .snapshot-pane h2 {
  font:550 14px/1.5 var(--font-display); margin:0;
}
.dsh-context-snapshot-bar .pane-caption {
  color:var(--muted); font-size:11px; margin:4px 0 14px;
}
.dsh-context-snapshot-bar .snapshot-detail {
  max-height:none; padding:0; overflow:visible;
}
.dsh-context-snapshot-bar .section-head,
.dsh-context-snapshot-bar .copy-row {
  flex-direction:column; align-items:flex-start; gap:6px;
}
.dsh-context-snapshot-bar .section-name {
  text-align:left;
}
.dsh-context-snapshot-bar .sidebar-demo {
  border-top:1px solid var(--border); flex:none; background:var(--surface-soft);
}
.dsh-context-snapshot-bar .sidebar-demo>summary {
  padding:12px 16px; min-height:44px; cursor:pointer; font-size:12px; color:var(--fg);
}
.dsh-context-snapshot-bar .demo-panel {
  display:block; padding:0 16px 16px; border:0; max-height:220px; overflow:auto;
}
.dsh-context-snapshot-bar .demo-panel h3,
.dsh-context-snapshot-bar .demo-eyebrow,
.dsh-context-snapshot-bar .demo-list,
.dsh-context-snapshot-bar .demo-divider {
  display:none;
}
.dsh-context-snapshot-bar .demo-panel p {
  margin:0 0 10px; font-size:11px;
}
.dsh-context-snapshot-bar .demo-motion {
  margin-top:12px;
}
.dsh-context-snapshot-bar .demo-button,
.dsh-context-snapshot-bar .copy-button,
.dsh-context-snapshot-bar select,
.dsh-context-snapshot-bar .send,
.dsh-context-snapshot-bar .quiet-icon {
  min-height:44px;
}
.dsh-context-snapshot-bar .quiet-icon,
.dsh-context-snapshot-bar .send {
  min-width:44px;
}
.dsh-context-snapshot-bar summary:focus-visible {
  outline:2px solid var(--accent); outline-offset:-3px;
}
.dsh-context-snapshot-bar [hidden] {
  display:none !important;
}
@media(max-width:1180px) {
  .dsh-context-snapshot-bar .app {
    grid-template-columns:174px minmax(0,1fr);
  }
  .dsh-context-snapshot-bar .conversation {
    grid-template-columns:minmax(0,1fr) 326px;
  }
  .dsh-context-snapshot-bar .topbar {
    padding:0 20px; gap:10px;
  }
  .dsh-context-snapshot-bar .composer-area {
    padding:0 16px 10px;
  }
}
@media(max-width:900px) {
  .dsh-context-snapshot-bar .app {
    grid-template-columns:minmax(0,1fr);
  }
  .dsh-context-snapshot-bar .sidebar {
    display:none;
  }
}
@media(max-width:600px) {
  .dsh-context-snapshot-bar .app {
    display:grid;
  }
  .dsh-context-snapshot-bar .main {
    grid-template-rows:58px minmax(0,1fr);
  }
  .dsh-context-snapshot-bar .conversation {
    grid-template-columns:minmax(0,1fr); grid-template-rows:minmax(0,1fr) minmax(0,40%);
  }
  .dsh-context-snapshot-bar .conversation.panel-closed {
    grid-template-rows:minmax(0,1fr);
  }
  .dsh-context-snapshot-bar .context-sidebar {
    border-left:0; border-top:1px solid var(--border);
  }
  .dsh-context-snapshot-bar .context-sidebar-header {
    display:none;
  }
  .dsh-context-snapshot-bar .context-tabs {
    position:relative; padding-right:48px; flex:none;
  }
  .dsh-context-snapshot-bar .mobile-close {
    position:absolute; right:5px; top:0; width:44px;
  }
  .dsh-context-snapshot-bar .context-sidebar-body {
    padding:8px 12px;
  }
  .dsh-context-snapshot-bar .trajectory-toggle {
    min-height:44px;
  }
  .dsh-context-snapshot-bar .trajectory-detail {
    padding:10px;
  }
  .dsh-context-snapshot-bar .messages {
    padding:20px 18px;
  }
  .dsh-context-snapshot-bar .assistant-message h2 {
    font-size:20px;
  }
  .dsh-context-snapshot-bar .message {
    margin-bottom:20px;
  }
  .dsh-context-snapshot-bar .composer-area {
    padding:0 12px 8px;
  }
  .dsh-context-snapshot-bar .composer {
    padding:9px;
  }
  .dsh-context-snapshot-bar .composer textarea {
    min-height:40px;
  }
  .dsh-context-snapshot-bar .snapshot-state {
    max-width:120px;
  }
  .dsh-context-snapshot-bar .demo-panel {
    max-height:120px;
  }
}
@media(min-width:601px) {
  .dsh-context-snapshot-bar .mobile-close {
    display:none;
  }
}
.dsh-context-snapshot-bar .context-node,
.dsh-context-snapshot-bar .tool-call,
.dsh-context-snapshot-bar .tool-result {
  display:grid; grid-template-columns:56px minmax(0,1fr); align-items:start; gap:8px; font-family:var(--font-body);
}
.dsh-context-snapshot-bar .node-kind {
  padding-top:1px; font-size:11px; line-height:1.6;
}
.dsh-context-snapshot-bar .node-body {
  font-size:12px; line-height:1.6; font-weight:400; overflow-wrap:anywhere;
}
.dsh-context-snapshot-bar .tool-result::before {
  content:none;
}
.dsh-context-snapshot-bar .compression-marker {
  position:relative; display:grid; grid-template-columns:18px minmax(0,1fr); gap:8px; padding:10px; border:1px dashed var(--border); border-radius:7px; background:var(--surface-soft); color:var(--fg);
}
.dsh-context-snapshot-bar .compression-marker-symbol {
  font-size:16px; line-height:1.5;
}
.dsh-context-snapshot-bar .compression-marker-label {
  font-size:11px; font-weight:550;
}
.dsh-context-snapshot-bar .compression-marker p {
  margin:3px 0; font-size:12px; line-height:1.6; overflow-wrap:anywhere;
}
.dsh-context-snapshot-bar .compression-marker-caption {
  font-size:10px; line-height:1.5; color:var(--muted);
}
.dsh-context-snapshot-bar .compression-marker.failed .compression-marker-symbol {
  color:var(--danger);
}
.dsh-context-snapshot-bar {
  --question-fill:oklch(0.96 0.022 256); --question-ink:oklch(0.39 0.08 256); --summary-fill:oklch(0.96 0.027 155); --summary-ink:oklch(0.37 0.07 155);
}
.dsh-context-snapshot-bar .round-intro {
  display:flex; justify-content:space-between; gap:8px; font-size:11px; color:var(--muted); margin:1px 0 14px;
}
.dsh-context-snapshot-bar .round-list {
  display:grid; gap:12px; min-width:0;
}
.dsh-context-snapshot-bar .turn-card {
  min-width:0; border:1px solid var(--border); border-radius:9px; background:var(--surface); overflow:hidden;
}
.dsh-context-snapshot-bar .turn-entry {
  width:100%; display:block; min-width:0; padding:12px; border:0; color:var(--question-ink); background:var(--question-fill); text-align:left;
}
.dsh-context-snapshot-bar .turn-entry:hover {
  background:oklch(from var(--question-fill) calc(l - .06) c h);
}
.dsh-context-snapshot-bar .trace-line {
  display:block; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; min-width:0; max-width:100%; font-size:12px; line-height:20px;
}
.dsh-context-snapshot-bar .turn-question {
  font-weight:550;
}
.dsh-context-snapshot-bar .turn-number {
  font-weight:600; margin-right:5px;
}
.dsh-context-snapshot-bar .turn-facts {
  font-size:11px; color:var(--question-ink); position:relative; padding-right:44px;
}
.dsh-context-snapshot-bar .turn-chevron {
  position:absolute; right:0; top:0; font-size:10px;
}
.dsh-context-snapshot-bar .turn-cycles {
  padding:8px; display:grid; gap:6px;
}
.dsh-context-snapshot-bar .trace-leaf {
  display:block; width:100%; min-width:0; padding:8px 10px; margin:0; border:1px solid var(--border); border-radius:6px; text-align:left; color:var(--fg); background:var(--surface);
}
.dsh-context-snapshot-bar button.trace-leaf {
  min-height:56px;
}
.dsh-context-snapshot-bar .trace-leaf .secondary {
  color:var(--muted); font-size:11px;
}
.dsh-context-snapshot-bar button.trace-leaf:hover {
  background:var(--surface-soft); border-color:var(--faint);
}
.dsh-context-snapshot-bar .cycle-node {
  border-color:transparent; background:var(--surface-soft);
}
.dsh-context-snapshot-bar .cycle-index {
  color:var(--muted); font:11px/20px var(--font-mono); margin-right:8px;
}
.dsh-context-snapshot-bar .cycle-info {
  display:grid; gap:5px; padding:6px 0 2px 10px; border-left:1px solid var(--border); margin:0 0 4px 12px;
}
.dsh-context-snapshot-bar .final-leaf {
  border:0;
}
.dsh-context-snapshot-bar .summary-entry,
.dsh-context-snapshot-bar .compression-event,
.dsh-context-snapshot-bar .summary-excerpt {
  background:var(--summary-fill); color:var(--summary-ink); border-color:oklch(from var(--summary-fill) calc(l - .13) c h);
}
.dsh-context-snapshot-bar .summary-entry .secondary,
.dsh-context-snapshot-bar .compression-event .secondary,
.dsh-context-snapshot-bar .summary-excerpt .secondary {
  color:var(--summary-ink);
}
.dsh-context-snapshot-bar button.summary-entry:hover {
  background:oklch(from var(--summary-fill) calc(l - .06) c h);
}
.dsh-context-snapshot-bar .compression-event {
  border-style:dashed;
}
.dsh-context-snapshot-bar .compression-event.failed {
  color:var(--danger); background:var(--surface-soft);
}
.dsh-context-snapshot-bar .compression-event.failed .secondary {
  color:var(--danger);
}
.dsh-context-snapshot-bar .summary-content {
  display:grid; gap:6px; margin-top:6px;
}
.dsh-context-snapshot-bar .system-anchor {
  border-style:dashed; color:var(--muted);
}
.dsh-context-snapshot-bar .archived {
  opacity:.7;
}
.dsh-context-snapshot-bar .round-footnote {
  color:var(--muted); font-size:11px; line-height:1.6; margin:14px 0 0;
}
.dsh-context-snapshot-bar .turn-card.contracting {
  animation:csb-turn-contract .5s ease both;
}
@keyframes csb-turn-contract {
to { opacity:0; transform:scale(.97); }
}
@media(prefers-color-scheme:dark) {
  .dsh-context-snapshot-bar {
    --question-fill:oklch(0.25 0.034 256); --question-ink:oklch(0.88 0.03 256); --summary-fill:oklch(0.25 0.033 155); --summary-ink:oklch(0.88 0.03 155);
  }
}
@media(prefers-reduced-motion:reduce) {
  .dsh-context-snapshot-bar .turn-card.contracting {
    animation:none;
  }
}
`
